name: log_removal
description: "A CLI tool for removing unwanted logs from Dart and Flutter projects."
version: 1.0.0+1
homepage: "https://github.com/naneps/log_removal"  

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  interact: ^2.2.0

dev_dependencies:




