name: log_removal
description: "A CLI tool for removing unwanted logs from Dart and Flutter projects."
version: 1.1.4
homepage: "https://github.com/naneps/log_removal"

executables:
  log_removal: log_removal

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dart_console: ^1.1.2
  interact: ^2.2.0
  

dev_dependencies:
  lints: ^2.0.0

platforms:
  windows:
  linux:
  web:
  android:
  macos: