name: log_removal
description: "A CLI tool for removing unwanted logs from Dart and Flutter projects."
version: 1.1.0
homepage: "https://github.com/naneps/log_removal"  


executables:
  log_removal: bin/log_removal.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  interact: ^2.2.0


dev_dependencies:
  ansicolor: ^2.0.3
  console: ^4.1.0
  lints: ^2.0.0