name: log_removal
description: "A CLI tool for removing unwanted logs from Dart and Flutter projects."
version: 1.1.1
homepage: "https://github.com/naneps/log_removal"  


executables:
  log_removal: log_removal

environment:
  sdk: '>=2.12.0 <4.0.0'


dependencies:
  dart_console: ^1.2.0
  interact: ^2.2.0


dev_dependencies:
  lints: ^2.0.0